/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Query */
        post: operations["run_query_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Query Stream */
        post: operations["run_query_stream_query_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/{trace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Query */
        get: operations["get_query_query__trace_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/{trace_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Review
         * @description Human-in-the-loop approve/reject/annotate action (roadmap §3.6) — can
         *     only be filed against a trace_id that actually completed a run, so a
         *     typo'd trace_id can't silently create an orphan review record.
         */
        post: operations["submit_review_query__trace_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/{trace_id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Reviews */
        get: operations["get_reviews_query__trace_id__reviews_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentResultResponse */
        AgentResultResponse: {
            /** Agent Name */
            agent_name: string;
            /** Answer */
            answer: string;
            /**
             * Citations
             * @default []
             */
            citations: components["schemas"]["Citation"][];
            /** Confidence */
            confidence: number;
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        };
        /** AuditTrail */
        AuditTrail: {
            /** Trace Id */
            trace_id: string;
            /** Query */
            query: string;
            /** Model Version */
            model_version: string;
            /** Agents */
            agents: string[];
            /** Timestamp */
            timestamp: string;
            token_usage?: components["schemas"]["TokenUsage"] | null;
            /** Estimated Cost Usd */
            estimated_cost_usd?: number | null;
        };
        /** Citation */
        Citation: {
            /** Chunk Id */
            chunk_id?: string | null;
            /** Source Reference */
            source_reference?: string | null;
            /** Source Regulation */
            source_regulation?: string | null;
            /** Similarity Score */
            similarity_score?: number | null;
            /** Excerpt */
            excerpt?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Detail */
            detail: string;
            /** Trace Id */
            trace_id?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Model Version */
            model_version: string;
            /** Llm Model */
            llm_model: string;
            /** Mlflow Tracking Uri */
            mlflow_tracking_uri?: string | null;
        };
        /** QueryRequest */
        QueryRequest: {
            /** Query */
            query: string;
            /**
             * Model Version
             * @description Overrides Settings.model_version for this request only.
             */
            model_version?: string | null;
        };
        /** QueryResponse */
        QueryResponse: {
            answer: components["schemas"]["AgentResultResponse"];
            summary: components["schemas"]["AgentResultResponse"];
            risk: components["schemas"]["AgentResultResponse"];
            /** Confidence */
            confidence: number;
            /**
             * Sources
             * @default []
             */
            sources: components["schemas"]["Citation"][];
            audit_trail: components["schemas"]["AuditTrail"];
        };
        /** ReviewRecord */
        ReviewRecord: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "approved" | "rejected";
            /** Reviewer Name */
            reviewer_name: string;
            /** Reviewer Role */
            reviewer_role?: string | null;
            /** Annotation */
            annotation?: string | null;
            /** Trace Id */
            trace_id: string;
            /** Timestamp */
            timestamp: string;
        };
        /**
         * ReviewRequest
         * @description Human-in-the-loop approve/reject/annotate action on a completed run
         *     (roadmap §3.6) — doubles as the per-answer compliance sign-off record
         *     docs/06 §4.10 calls for. `reviewer_name` is self-reported free text:
         *     this app has no auth/user-identity system, a deliberate, documented
         *     limitation (see docs/09), not an oversight.
         */
        ReviewRequest: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "approved" | "rejected";
            /** Reviewer Name */
            reviewer_name: string;
            /** Reviewer Role */
            reviewer_role?: string | null;
            /** Annotation */
            annotation?: string | null;
        };
        /** TokenUsage */
        TokenUsage: {
            /**
             * Prompt Tokens
             * @default 0
             */
            prompt_tokens: number;
            /**
             * Completion Tokens
             * @default 0
             */
            completion_tokens: number;
            /**
             * Embedding Tokens
             * @default 0
             */
            embedding_tokens: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    run_query_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    run_query_stream_query_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_query_query__trace_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_review_query__trace_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewRecord"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_reviews_query__trace_id__reviews_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewRecord"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
