services:
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: finance_compliance_rag_mlflow
    ports:
      - "5000:5000"
    volumes:
      - mlflow_data:/mlflow
    restart: unless-stopped

volumes:
  mlflow_data:
