"""
File-based audit store for completed orchestrator runs, keyed by trace_id
(roadmap §3.3's "durable audit log", scoped down to what `app/api.py`'s
`GET /query/{trace_id}` needs: a completed run's full result surviving an
API process restart. Not the SQLite/Postgres table the roadmap describes —
that's still open future work; this is a lightweight file store matching the
project's existing pattern for `data/*_cache/`).

`trace_id` is attacker-controlled input on the read path (`GET
/query/{trace_id}`), so callers MUST validate it against `TRACE_ID_RE`
before calling `load_audit_record` — this module does not sanitize its
input, to keep the path-traversal check visible at the HTTP boundary where
the untrusted value actually enters the system.
"""

import json
import re
from pathlib import Path
from typing import Any, Dict, Optional

from src.config import get_settings

settings = get_settings()

# trace_id is generated by `new_trace_id()` (uuid4().hex) — 32 lowercase hex
# chars. Anything else is rejected before it ever reaches the filesystem.
TRACE_ID_RE = re.compile(r"^[0-9a-f]{32}$")


def _path_for(trace_id: str) -> Path:
    if not TRACE_ID_RE.match(trace_id):
        raise ValueError(f"Invalid trace_id: {trace_id!r}")
    root = settings.resolved(settings.audit_log_path)
    root.mkdir(parents=True, exist_ok=True)
    return root / f"{trace_id}.json"


def save_audit_record(trace_id: str, record: Dict[str, Any]) -> None:
    _path_for(trace_id).write_text(
        json.dumps(record, default=str, indent=2), encoding="utf-8"
    )


def load_audit_record(trace_id: str) -> Optional[Dict[str, Any]]:
    path = _path_for(trace_id)
    if not path.exists():
        return None
    return json.loads(path.read_text(encoding="utf-8"))
